### ISSUE TITLE
Checklist window does not open on dual-screen setup

### ISSUE THREAD

**Issue by sdusor** [patrickl92/AudioChecklist#4] opened 2022-01-21 02:38 UTC
Hello Patrick,

Only "Audio Checklist - Preferences" command works and shows up on the screen. The other two, "Audio Checklist: Show Window" and Audio Checklist : Switch SOP" are listed but do not appear on the screen when clicked on.

Thank you,
LG

**Comment by prokopiu** [comment] 2022-01-21 06:41
Hi, I had similar issues because I had overlooked that Audiochecklist does not come with a SOP. You need to jump to patrick's second repository and download one of the currently 2 SOP Zips and install them. After that it worked fine (Restart FlyWithLua or X-Plane so that it picks up the changes). Maybe that is your problem? https://github.com/patrickl92/AudioChecklistSOPs/releases/tag/v1.1.1

**Comment by patrickl92** [comment] 2022-01-21 08:17
Hi, the command "Audio Checklist: Switch SOP" does not show any window. It just resets the selected SOP, if you had select one. The option "Audio Checklist: Show Window" should show the SOP selection window. Is the window not showing at all, or is there just no SOP available?

**Comment by sdusor** [comment] 2022-01-21 11:54
Prokopu,
Thanks for the suggestion. The SOP is already installed.  I only downloaded "B737_ZiboDefault.zip" and extracted the contents of the script folder "AudioChecklist_B737_ZiboDefault.lua" file and  "AudioChecklists" folder to " ..\X-Plane 11\Resources\plugins\FlyWithLua\Scripts" folder.

Patrick92,
As I mention above, the SOP is installed. The actual window for the option "Audio Checklist: Show Window" is not showing. 
Now, I do have a dual monitor setup. And, I've see in the past that some plugins do not show on the screen at all or are almost off screen. I could never get the AviTab to show when both monitors are running XP11. Works fine with just one monitor. Maybe related?

Thank you

**Comment by patrickl92** [comment] 2022-01-21 18:10
That could be an issue. How do you have that configured in X-Plane? I'll try to reproduce that. I also have two monitors, but I'm using only one for X-Plane.
Have you tried to switching to only one monitor and see if it works? I'm not sure if your note that it works with just one monitor refers to AviTab or AudioChecklist.

**Comment by sdusor** [comment] 2022-01-21 18:37
That was my next step, to try it only with one monitor. Also with a clean copy of XP11 and only FWL plugin and Zibo mod loaded. I ran out of time this morning but will try it later today.  But at the same time, the fact that the  "Audio Checklist - Preferences" window works fine makes me think that I'm missing something else. 

I was referring to Avitab working fine with just one monitor.

**Comment by patrickl92** [comment] 2022-01-21 18:59
I've just publish a new release, which allows you to enable debug loggin using the menu entry `Plugins > FlyWithLua > FlyWithLua Macros > Audio Checklist: Enable Debug Logging`. Please download this release and activate this option before opening the AudioChecklist window. This will now print the location of the window into the log file of X-Plane. After that, please provide the log file here. It is located in the X-Plane directory, named `Log.txt`.

Note that the debug logging will always be disabled per default when starting X-Plane or selecting another aircraft.

**Comment by sdusor** [comment] 2022-01-21 19:10
Will do and report back. Thank you

**Comment by sdusor** [comment] 2022-01-22 01:03
Patrick,

So, with only one monitor used for XP11, "Audio Checklist: Show Window" works fine. I tried it first with a bare minimal install of xp11 with only FWL and Zibo loaded and then again with all of my other plugins and sceneries. Both cases were configured to only use one monitor.

As soon as I went back to 2 monitor configuration the issue reappeared: "Audio Checklist: Show Window" not displayed.

Attached is the debug log.txt


Thank you
[Log.txt](https://github.com/patrickl92/AudioChecklist/files/7917344/Log.txt)

**Comment by patrickl92** [comment] 2022-01-26 21:03
Thank you for testing this out. I don't specify an initial location for the checklist window. X-Plane then places it near the upper left corner. This does not work correctly if the two screens have a different resolution. This is your case:

![grafik](https://user-images.githubusercontent.com/16118262/151246164-f2a37c3a-0467-4bae-acba-7fa3e006b729.png)

The dotted rectangle is the virtual screen size of X-Plane. This means if it places the window somewhere in the upper left corner, it is actually outside of the left monitor (red rectangle). I need to check how to find out whether the window is actually visible at its current location (this is already checked, but only works if both screens have the same resolution).

**Comment by sdusor** [comment] 2022-01-26 21:16
Thank you so much for investigating this issue. I was suspecting that different resolutions are the cause. And, like I mention before Avitab behaves the same way but not any other plugin. Hopefully, it is fixable within the constraints of FWL.

**Comment by patrickl92** [comment] 2022-01-27 21:17
Can you please try if the following fixes that issue for you? Copy the lua file in the ZIP to the FlyWithLua Scripts directory and overwrite the existing file.

[AudioChecklist_Fix.zip](https://github.com/patrickl92/AudioChecklist/files/7953846/AudioChecklist_Fix.zip)

**Comment by sdusor** [comment] 2022-01-28 14:31
Tried it last night and it worked! The window popped up in the top left corner on the left monitor (1920x1080). I'll start using it now but if there is something specific you would like me to test with my configuration please let me know. Thank you very much!

**Comment by patrickl92** [comment] 2022-01-28 14:36
Great, it will be part of the next release. The preferences window will be also centered on the main monitor instead of the virtual X-Plane screen size (that is not part of the file I sent you).

**Comment by sdusor** [comment] 2022-01-28 14:47
Just a suggestion here... if possible and it makes sense to you too, to have all windows open on the same monitor. My _personal_ preference, for my configuration, is that all windows would open on the left monitor (1920x1080).  Also, I'm using X-camera plugin. And there, there is an option there to specify the monitor to use for pop-up windows. Not really a big deal, just makes it more consistent. 
Again, Thank you very much for this great addition to XP11!

**Comment by patrickl92** [comment] 2022-01-28 14:56
My last comment was a bit misleading. Both windows will now open in the main monitor. This is the monitor that also shows the X-Plane menu bar. So if you would set your right monitor as the main monitor in Windows, then both windows will be opened there (checklist window near the upper left corner, preferences window centered). I think that should work quite well.

**Comment by sdusor** [comment] 2022-01-28 15:34
Thanks for clarifying. 
Sounds like in my case windows will appear on the right monitor (4k). It's where my X-Plane menu bar (while in the cockpit) shows up. However, it is set up as monitor 2 in Windows OS and monitor 1 in XP11 (see attached image). I don't remember how I managed to get monitor 1 to act as the main monitor. Either way, having windows appear on the same monitor would be great.

![Capture](https://user-images.githubusercontent.com/98137280/151573310-ed755aad-8d67-4701-85cb-709b9421bb2b.PNG)

**Comment by patrickl92** [comment] 2022-01-28 18:23
Good to know, I thought the main monitor in Windows is also the monitor which X-Planen uses for the menu. Since this hasn't to be the case, I guess adding an option to select the preferred monitor is a good idea. The idea is that the windows will open on the preferred monitor, but can be dragged on any other monitor too. As long as X-Plane is opened and no other plane is loaded, the position of the checklist window will be restored if it is closed and opened again. The preferences window will always open at the center of the preferred monitor.

**Comment by patrickl92** [comment] 2022-01-28 20:55
I have added the selection of the preferred monitor to the preferences window. It works as described above. Could you please take a look with you configuration?

[AudioChecklist_SelectPreferredMonitor.zip](https://github.com/patrickl92/AudioChecklist/files/7961762/AudioChecklist_SelectPreferredMonitor.zip)

**Comment by sdusor** [comment] 2022-01-29 20:06
Yes, it works. Thank you!

**Closed as completed** 2022-01-29 21:03 UTC
Labels: bug
